export const LOSS_VALUE_GOOD_THRESHOLD = 1;
export const LOSS_VALUE_BAD_THRESHOLD = 2;

export const FITNESS_ALPHA = 0.5;

export const BAD_SIMULATION_RETRIES_ENABLED = true;
export const BAD_SIMULATION_BATCH_INDEX_CHECK = 1;
export const BAD_SIMULATION_RETRIES_NUM = 1;
export const BAD_SIMULATION_MIN_LOSS_INCREASE_PERCENTAGE = 110;
